# Generated by Django 4.1 on 2022-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2', models.FloatField()),
                ('time', models.TimeField()),
                ('psfc', models.FloatField()),
                ('rainc', models.FloatField()),
                ('rainnc', models.FloatField()),
                ('clflo', models.FloatField()),
                ('clfmi', models.FloatField()),
                ('clfhi', models.FloatField()),
                ('rh2', models.FloatField()),
                ('whi10', models.FloatField()),
                ('wd10', models.FloatField()),
            ],
        ),
    ]
