# Generated by Django 4.1 on 2022-08-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0004_alter_disasters_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Disasters",
        ),
    ]
