# Generated by Django 4.1 on 2022-08-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
