# Generated by Django 4.1 on 2022-08-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disasters",
            options={"managed": False},
        ),
    ]
